# Generated by Django 4.0.4 on 2022-05-13 16:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('location', models.CharField(max_length=255, verbose_name='Город')),
                ('logo', models.CharField(blank=True, max_length=255, verbose_name='Логотипчик')),
                ('description', models.TextField(blank=True, verbose_name='Информация о компании')),
                ('employee_count', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество сотрудников')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('picture', models.CharField(blank=True, max_length=255, verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('skills', models.CharField(max_length=255, verbose_name='Навыки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Зарплата от')),
                ('salary_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='Зарплата до')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Опубликовано')),
                ('company', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.company', verbose_name='Компания')),
                ('specialty', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.specialty', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
