# Generated by Django 4.0.4 on 2022-05-24 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0006_alter_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('surname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('status', models.CharField(choices=[('DLF', 'Не ищу работу'), ('CSR', 'Рассматриваю предложения'), ('LF', 'Ищу работу')], default='LF', max_length=3, verbose_name='Готовность к работе')),
                ('salary', models.IntegerField(verbose_name='Вознаграждение')),
                ('grade', models.CharField(choices=[('IN', 'Стажер'), ('JN', 'Джуниор'), ('MD', 'Миддл'), ('SN', 'Синьор'), ('LD', 'Лид')], max_length=2, verbose_name='Квалификация')),
                ('education', models.CharField(max_length=255, verbose_name='Образование')),
                ('experience', models.CharField(max_length=255, verbose_name='Опыт работы')),
                ('portfolio', models.CharField(max_length=128, verbose_name='Портфолио')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='vacancies.specialty', verbose_name='Специальность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
